### PR TITLE
Cleanup for unused functions

### PR DESCRIPTION
**Pull request by ntfshard**

### CODE REVIEW

**Comment by Dale-Koenig** [comment]
Please make PRs to devel
(You can leave the ones to 0.9.4 as we may merge them there too but we definitely need them to devel either way)

**Comment by ntfshard** [comment]
> Please make PRs to devel (You can leave the ones to 0.9.4 as we may merge them there too but we definitely need them to devel either way)

I thought to cherry-pick it to devel from this branch

**Comment by Dale-Koenig** [comment]
We seem to not have CI set up for release branch, so please make PRs to devel

**Comment by ntfshard** [comment]
> We seem to not have CI set up for release branch, so please make PRs to devel

Now I see, https://github.com/rapyuta-robotics/alica/pull/387

but diffs is smaller in devel branch, seems already cleaned part of it

**Comment by triccyx** [comment]
There are some already removed methods. 
??

**Comment by triccyx** [comment]
Ah sorry, I haven't noticed that you don't merge over devel but over 0.9.4. Is this ok?

**Comment by ntfshard** [comment]
We want to merge it? Due it's a minor changes and it's not a mainstream, I believe we could skip it changes here

**Comment by Dale-Koenig** [comment]
> We want to merge it? Due it's a minor changes and it's not a mainstream, I believe we could skip it changes here

I think it's not necessary for release branch

**Pull request closed without merging**
