### PR TITLE
Eliminate codegen from behaviors in supplementary tests

### PR DESCRIPTION
**Pull request by triccyx**
- Remove cod gen tags
- Add dynamic loading methods

### CODE REVIEW

**Comment by triccyx** [comment]
I think we can also remove DomanBehaviour

**Review by ntfshard — COMMENTED** [review]
less code is better! But we already removed codegen? Or this changes won't break it?

**Comment by triccyx** [comment]
Yes, @ntfshard the changes are safe in this PR.

**Review by Dale-Koenig — APPROVED** [review]

**Comment by Dale-Koenig** [comment]
> I think we can also remove DomanBehaviour

Yes if it isn't used feel free to

**Review by david-simoes-93 — APPROVED** [review]

**Review by ntfshard — APPROVED** [review]

**Pull request merged**
