### PR TITLE
Added test compilation logic

### PR DESCRIPTION
**Pull request by dhananjay-patki**
Put all tests behind BUILD_TESTING cmake flag. Use -DBUILD_TESTING=OFF as a CMake argument to disable the building of tests.

### CODE REVIEW

**Review by triccyx — APPROVED** [review]

**Comment by Dale-Koenig** [comment]
From CI logs, it looks like there are a lot of build warnings now

**Comment by dhananjay-patki** [comment]
> From CI logs, it looks like there are a lot of build warnings now


The only error I'm seeing on travis is this:

```
Exception in callback _UnixReadPipeTransport._read_ready()
handle: <Handle _UnixReadPipeTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 500, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3/dist-packages/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py", line 109, in data_received
    protocol.on_stderr_received(data)
  File "/usr/lib/python3/dist-packages/catkin_tools/execution/io.py", line 269, in on_stderr_received
    self.log_file.write(data)
ValueError

```
Which is from a older merged PR. CMake does get annoyed when you do pass in that flag, but from what I've read it's an intended quirk.

**Comment by Dale-Koenig** [comment]
> > From CI logs, it looks like there are a lot of build warnings now
> 
> The only error I'm seeing on travis is this:
> 
> ...
> Which is from a older merged PR. CMake does get annoyed when you do pass in that flag, but from what I've read it's an intended quirk.

I'm more worried about

>Warnings   << alica_engine:findtest /root/catkin_ws/logs/alica_engine/test.findtest.000.log
> make: *** No rule to make target 'test'.  Stop.

Which seems related to this PR

**Comment by dhananjay-patki** [comment]
> > > From CI logs, it looks like there are a lot of build warnings now
> > 
> > 
> > The only error I'm seeing on travis is this:
> > ...
> > Which is from a older merged PR. CMake does get annoyed when you do pass in that flag, but from what I've read it's an intended quirk.
> 
> I'm more worried about
> 
> > Warnings   << alica_engine:findtest /root/catkin_ws/logs/alica_engine/test.findtest.000.log
> > make: *** No rule to make target 'test'.  Stop.
> 
> Which seems related to this PR

The other PRs have that warning as well, but the alica_engine package itself doesn't actually have any tests in it, so I don't think it's actually a problem. The other packages that don't have tests in them also have that message.

**Comment by Dale-Koenig** [comment]
https://www.wrike.com/open.htm?id=987839279

**Review by Dale-Koenig — APPROVED** [review]

**Pull request merged**
