### PR TITLE
Remove alica tests from ros1 folder

### PR DESCRIPTION
**Pull request by rogeriofonteles**
Wrike: https://www.wrike.com/open.htm?id=1066483984

### CODE REVIEW

**Review by Dale-Koenig — APPROVED** [review]

**Comment by ntfshard** [comment]
I have a question. Why PR caption starts from Remove but inside it's a renaming?

**Comment by Dale-Koenig** [comment]
As per comment on wrike task, please wait until codegen relics are removed

**Review by david-simoes-93 — COMMENTED** [review]
Please re-request review when rebased and ready

**Comment by Dale-Koenig** [comment]
Can now be remade

**Pull request closed without merging**
