### PR TITLE
Turtlesim with value mapping and implementationName

### PR DESCRIPTION
**Pull request by Dale-Koenig**
Somewhat significant plan change: Turtles immediately join formation and need to be told to leave, rather than waiting for a topic pub to join.  
Introduces classes TracedPlan and UntracedPlan in alica_standard_library which can be used as the implementation name of plans that need no implementation.  Note that MakeFormation, which has a custom condition/constraint, still needs its own exports until/unless we add libraryName as a field for conditions
Screenshot from 2023-03-07 11-33-39

### CODE REVIEW

**Comment by rogeriofonteles** [comment]
What was the problem with the old behavior?

**Comment by Dale-Koenig** [comment]
> What was the problem with the old behavior?

Actually it may have been fine.  I though it was a bit weird that the agent would teleport to a random position any time it left formation, but it may have been intentional

**Comment by Dale-Koenig** [comment]
> What was the problem with the old behavior?

Sorry if you mean with the behaviour of not joining right away, it's just inconvenient.  With the new behaviour I can run with 20 turtles and immediately see them all join the formation rather than sending them in one by one

**Comment by Dale-Koenig** [comment]
I think actually I'll make the robots go to a fixed spot in the corner when they leave formation

**Review by veerajsk — APPROVED** [review]

**Pull request merged**
