### PR TITLE
Fix precision error in ros clock sleep

### PR DESCRIPTION
**Pull request by veerajsk**
ros clock used AlicaTime::inSeconds() to convert
the duration of the sleep to seconds. However, this works out to 0 for any time interval < 1 sec. Since the sleep time is 33 ms in step engine, this can
cause problems. Futher, this rounding behaviour
is not intuitive for users of the clock in general

More details here: https://rapyuta-robotics.slack.com/archives/C01BRTPRCF5/p1729678490966409

### CODE REVIEW

**Review by AsturaPhoenix — COMMENTED** [review]
Humbly request that this PR also change the Alica test context stepEngine to use wall time instead of Alica time so that this doesn't break our fake time tests:

https://github.com/rapyuta-robotics/alica/blob/209b61e5d3582647c541837395b483454c50582f/alica_engine/src/engine/AlicaContext.cpp#L137-L151

context: https://rapyuta-robotics.slack.com/archives/C061W8L5M3N/p1728112390979819?thread_ts=1728102684.080249&cid=C061W8L5M3N

**Review by bjoernschroeder — APPROVED** [review]
Change is looking good to me

**Comment by bjoernschroeder** [comment]
@AsturaPhoenix Im not getting the issue with stepEngine from the slack discussion. You have tests which manipulate simulated time (increase to 10x speed?) and because of that stepEngine is returning too fast? You want it to maintain the set alica frequency in real world time, even if sim time differs?

If you want it to use real world time, you could inject AlicaClock instead of AlicaROSClock, which uses system time, or inject your own AlicaROSWallTimeClock. Would that solve the issue youre facing with stepEngine?

**Comment by veerajsk** [comment]
+1 to Bjoern comment. I don't understand what exactly is the issue you are facing either.

**Comment by veerajsk** [comment]
actually what clock is used doesn't really matter in stepEngine, because the timeout is checked using system_clock anyway. Just the sleep time is affected which does not really matter

**Comment by AsturaPhoenix** [comment]
We're stepping sim time within the tests themselves in the interest of maximizing determinism. The problem with using the Alica clock to sleep 33 ms while also using a sim (ROS) time Alica clock is that it then forces us to step time during this sleep in order to not deadlock, which starts to undermine the determinism. We'd effectively have to step time in a loop like real time (or at best accelerated real time) until the step completes.

**Comment by bjoernschroeder** [comment]
That makes sense and I can see the issue. However, I dont think AlicaContext should be changed to use real world time. The AlicaContext itself should stick with whatever clock was injected during construction.

For your specific usecase, you should be able to inject a clock which uses ros::WallTime during sleep without issues. You can still use ros::Time for your now()

**Comment by AsturaPhoenix** [comment]
Isn't the motivation for the sleep in order to give other threads a chance to reach a synchronization point? Or are there other AlicaClock sleeps in there somewhere that sleep in Alica time to some duration totaling around 33 ms?

(Further evidence towards this interpretation is the observation that the timeout is in real time.)

FWIW, we're seeing a maximum speedup factor of just over 10x even with complete fake time, which actually seems low, so I do wonder whether there really is a real time component to how long Alica engine steps take.

Changing the step sleep to use real time would actually further make our tests slower I think (unless steps really are somehow still taking 33 ms despite fake time), which is unfortunate so I'm inclined to take your advice, though I'm not entirely sure how to do it without messing with any sleeps Alica is doing in legitimate Alica time, aside from special-casing 33 ms. :stuck_out_tongue:

**Comment by veerajsk** [comment]
Yes, the sleep is just to wait until the alica main engine thread has finished executing its tick cycle. Doesn't really matter how much time we sleep for because we keep check if the tick is done or not & the sleep is only there to avoid continuously looping in the while loop. I guess 33 ms is an estimated time for one tick to complete, so that's the amount of time it sleeps for. (I'm not sure how this time was estimated, it has been that way since before I got into alica I think)
Actually this 33 ms is estimated in real time I think, because alica existed before we even added a ros clock, so was likely just using system time before

**Comment by bjoernschroeder** [comment]
The only other place the engine is sleeping internally is when not using manual stepping, to maintain frequency. It should only impact behaviours and plans which use alica clock for sleeping.

Default value is 33ms probably because we use an engine frequency of 30 in our tests and might have used this frequency in projects in the beginning.

**Review by ChristofDubs — APPROVED** [review]

**Pull request merged**
