### PR TITLE
Luca refactoring PR2 bis

### PR DESCRIPTION
**Pull request by triccyx**
Removed AlicaEngine::this from TeamObserver and related classes.

### CODE REVIEW

**Comment by abhi1287** [comment]
Lets just move engine construction to Init of AlicaContext and you don't need to add any of this. + we can remove AlicaContext dependency from AlicaEngine as well. 

Here is how this would work:
Applications are allowed to set clock, communicator, tracefactory etc after construction of AlicaContext and before its init().  By delaying engine construction to the init of AlicaContext, we could be sure that all the necessary stuff has already been set so we don't need to do this back and forth between various components. Then to AlicaEngine and other internal components, you can just pass references of the things owned by AlicaContext.

Also, pl add a check in all AlicaContext setters (other than config)  that they can only be called before engine is initialized or after it has been stopped.

**Comment by triccyx** [comment]
> Lets just move engine construction to Init of AlicaContext and you don't need to add any of this. + we can remove AlicaContext dependency from AlicaEngine as well.
> 
> Here is how this would work: Applications are allowed to set clock, communicator, tracefactory etc after construction of AlicaContext and before its init(). By delaying engine construction to the init of AlicaContext, we could be sure that all the necessary stuff has already been set so we don't need to do this back and forth between various components. Then to AlicaEngine and other internal components, you can just pass references of the things owned by AlicaContext.
> 
> Also, pl add a check in all AlicaContext setters (other than config) that they can only be called before engine is initialized or after it has been stopped.


Ok, clear I will follow this way, good idea.
Just one thing I do not like:
using std::unique_ptr and spreading references or internal ptr around, I would prefer to change to std::shared_ptr.
It could be dangerous and it looks like a trick to not use shared_ptr. Is there a reason? @abhi1287 ?

**Comment by abhi1287** [comment]
> > Lets just move engine construction to Init of AlicaContext and you don't need to add any of this. + we can remove AlicaContext dependency from AlicaEngine as well.
> > Here is how this would work: Applications are allowed to set clock, communicator, tracefactory etc after construction of AlicaContext and before its init(). By delaying engine construction to the init of AlicaContext, we could be sure that all the necessary stuff has already been set so we don't need to do this back and forth between various components. Then to AlicaEngine and other internal components, you can just pass references of the things owned by AlicaContext.
> > Also, pl add a check in all AlicaContext setters (other than config) that they can only be called before engine is initialized or after it has been stopped.
> 
> Ok, clear I will follow this way, good idea. Just one thing I do not like: using std::unique_ptr and spreading references or internal ptr around, I would prefer to change to std::shared_ptr. It could be dangerous and it looks like a trick to not use shared_ptr. Is there a reason? @abhi1287 ?

shared_ptr pollutes the ownership and should never be used unless there is absolute need. Owner of the object should just store it as unique pointers and give references around if the parent is guaranteed to outlive all other internal users.

**Comment by triccyx** [comment]
ok

**Comment by triccyx** [comment]
May I assume that once the clock/communicator etc ...  is assigned it can not be reassigned with a different one after AlixaContext::init? @abhi1287

**Comment by abhi1287** [comment]
it can be reassigned any number of times before init() is called, not after init.

**Comment by triccyx** [comment]
ok, one last thing. I'm checking but at least one test should be changed (test_alica.h:148) at the moment I'm there

**Comment by triccyx** [comment]
See new [PR](https://github.com/rapyuta-robotics/alica/pull/282)

**Pull request closed without merging**
