### PR TITLE
Setup tracing after blackboard

### PR DESCRIPTION
**Pull request by veerajsk**
Setup the blackboard before tracing so that blackboard values can be
used in settup up custom tracing

### CODE REVIEW

**Review by christianhelm — APPROVED** [review]

**Review by Prajapati-Pawan — APPROVED** [review]

**Review by Dale-Koenig — APPROVED** [review]

**Comment by Prajapati-Pawan** [comment]
@Dale-Koenig @veerajsk the change is made on top of rr_devel and as conditions repo change is not merged for di_core, is there a way we can get just this change on top of alica submodule version used in di_core.

**Comment by veerajsk** [comment]
> @Dale-Koenig @veerajsk the change is made on top of rr_devel and as conditions repo change is not merged for di_core, is there a way we can get just this change on top of alica submodule version used in di_core.

can maybe create a temporary branch & cherry pick this change to it? Or we could make a 0.9.3 release with all the backboard changes excluding conditions

**Comment by Dale-Koenig** [comment]
> > @Dale-Koenig @veerajsk the change is made on top of rr_devel and as conditions repo change is not merged for di_core, is there a way we can get just this change on top of alica submodule version used in di_core.
> 
> can maybe create a temporary branch & cherry pick this change to it? Or we could make a 0.9.3 release with all the backboard changes excluding conditions

Yeah just making a new 0.9.3 branch is fine I think

**Comment by veerajsk** [comment]
> > > @Dale-Koenig @veerajsk the change is made on top of rr_devel and as conditions repo change is not merged for di_core, is there a way we can get just this change on top of alica submodule version used in di_core.
> > 
> > 
> > can maybe create a temporary branch & cherry pick this change to it? Or we could make a 0.9.3 release with all the backboard changes excluding conditions
> 
> Yeah just making a new 0.9.3 branch is fine I think

okay, I'll make the release branch

**Pull request merged**
